name: falling_box
description: a game with falling boxes

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.12.0
